# Default values for blog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  repository: quay.io/srcd/blog
  # tag must be received as a parameter
  pullPolicy: IfNotPresent
service:
  name: blog-service
  type: NodePort
  externalPort: 80
  internalPort: 80
ingress:
  enabled: true
  # globalStaticIpName must be received as a parameter
  # hostname must be received as a parameter
  # hosts defined in templates/ingress.yml. Do not override here.
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.global-static-ip-name is defined in templates/ingress.yml. Do not override here.
  tls: true
    # secretName and hosts are defined in templates/ingress.yml. Do not override here.

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious 
  # choice for the user. This also increases chances charts run on environments with little 
  # resources, such as Minikube. If you do want to specify resources, uncomment the following 
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi
