title: source{d} blog
theme: hugo-steam-theme

languageCode: en

taxonomies:
  category: "categories"

author:
  name: source{d}
  email: hello@sourced.tech

params:
  description: Building the first AI that understands code
  copyright: Copyright (c)
  themeColor: custom
  RSSlink: /index.xml

  title: "source{d} blog"
  subtitle: "Building the technology stack for AI on code"

  # You can choose between green, orange, red and blue.
  # Enable Google Analytics be inserting your tracking code
  googleAnalytics: "UA-69608223-2"

  # To provide some metadata for search engines and the about section in the footer
  # feel free to add a few information about you and your website.
  name: "source{d}"
  bio: "Building the technology stack for AI on code"
  location: ""
  twitter: "sourcedtech"
  github: "src-d"
  medium: source-d
  angellist: source-d
  linkedin: 10284920
  slack_url: //sourced.tech/api/invite

  # Enable a comment system
  # You can choose between Disqus or Google Plus by setting comments
  # to disqus or googleplus. For using Disqus you need to enter your
  # shortname in disqusShortname at the top of the configs.
  comments: "disqus"

  # Customize or translate the strings
  keepReadingStr: "Keep reading"
  backtotopStr: "Back to top"
  shareStr: "Share"
