title: source{d} blog
theme: hugo-steam-theme

taxonomies:
  category: "categories"

params:
  description: Building the first AI that understands code
  copyright: The MIT License. - Copyright (c) 2016 source{d}
  themeColor: custom
  RSSlink: /index.xml

  title: "source{d} blog"
  subtitle: "Building the first <b>AI</b> that <b>understands code</b>"
  copyright: "For developers, By developers"

  # You can choose between green, orange, red and blue.
  # Enable Google Analytics be inserting your tracking code
  googleAnalytics: "UA-69608223-2"

  # To provide some metadata for search engines and the about section in the footer
  # feel free to add a few information about you and your website.
  name: "source{d}"
  bio: "Building the first AI that understands code"
  location: "" # optional
  twitter: "srcd_" # optional
  github: "src-d" # optional

  # Enable a comment system
  # You can choose between Disqus or Google Plus by setting comments
  # to disqus or googleplus. For using Disqus you need to enter your
  # shortname in disqusShortname at the top of the configs.
  comments: "disqus"

  # Customize or translate the strings
  keepReadingStr: "Keep reading"
  backtotopStr: "Back to top"
  shareStr: "Share"
  pageNotFoundTitle: "404 - Page not found"

  authors:
    mcuadros:
      name: Máximo Cuadros
      thumbnail: https://avatars1.githubusercontent.com/u/1573114?v=3&s=460
      bio: "(╯°□°）╯︵ ┻━┻"
      social:
        github: mcuadros
        twitter: mcuadros_
    dripolles:
      name: Daniel Ripollés
      thumbnail: https://avatars1.githubusercontent.com/u/768061?v=3&s=460
      bio: Thinking Hard Driven Development / Loving Python, learning Haskell
      social:
        github: dripolles
        twitter: leidan
    alcortesm:
      name: Alberto Cortés
      thumbnail: https://avatars3.githubusercontent.com/u/9169414?v=3&s=460
      bio: Learning Go (both of them).
      social:
        github: alcortesm
    ikanor:
      name: Franky Rodriguez
      thumbnail: https://avatars2.githubusercontent.com/u/5469238?v=3&s=460
      bio: Computer scientist. Amateur musician. I like math.
      social:
        github: ikanor
        twitter: minifranky
    erizocosmico:
      name: Miguel Molina
      thumbnail: https://avatars3.githubusercontent.com/u/1312023?v=3&s=460
      bio: "I write code."
      social:
        github: erizocosmico
    scaleyourcode:
      name: Christophe Limpalair
      thumbnail: https://avatars3.githubusercontent.com/u/6696921?v=3&s=460
      bio: "Christophe enjoys sitting down with CTOs and top developers to learn how they work, and sharing that knowledge with the rest of the world. He does this through his podcast called ScaleYourCode."
      social:
        github: christophelimpalair
        twitter: ScaleYourCode
    eiso:
      name: Eiso Kant
      thumbnail: https://avatars2.githubusercontent.com/u/1247608?v=3&s=460
      bio: "Passion for neural networks. Python to get things done, learning Haskell for fun."
      social:
        github: eiso
        twitter: eisokant
    vadim:
      name: Vadim Markovtsev
      thumbnail: https://avatars0.githubusercontent.com/u/2793551?v=3&s=460
      bio: "A former system programmer, Vadim is now a machine learning engineer in love with deep neural networks."
      social:
        github: vmarkovtsev
        twitter: tmarkhor
    smola:
      name: "Santiago M. Mola"
      thumbnail: https://avatars1.githubusercontent.com/u/23248?v=3&s=460
      bio: "Developing data stuff."
      social:
        github: smola
        twitter: mola_io
    waren:
      name: "Waren Long"
      thumbnail: https://avatars2.githubusercontent.com/u/24694845?v=3&s=460
      bio: "Machine learning intern"
      social:
        github: warenlg
        twitter: warenlg
