title: source{d}
baseUrl: /

params:
  description: coding to find awesome engineers
  copyright: The MIT License. - Copyright (c) 2015 Máximo Cuadros
  themeColor: custom

  title: "source{d}"
  subtitle: "coding to find awesome engineers"
  copyright: "Product by Tyba • Crafted with love."

  # You can choose between green, orange, red and blue.
  # Enable Google Analytics be inserting your tracking code
  googleAnalytics: ""

  # To provide some metadata for search engines and the about section in the footer
  # feel free to add a few information about you and your website.
  name: "source{d}"
  bio: "I'm just a theme. That's it. If you like my design clone [me](//github.com/digitalcraftsman/hugo-steam-theme) from Github. Thanks."
  location: "" # optional
  twitter: "srcd_" # optional
  github: "src-d" # optional

  # Enable a comment system
  # You can choose between Disqus or Google Plus by setting comments
  # to disqus or googleplus. For using Disqus you need to enter your
  # shortname in disqusShortname at the top of the configs.
  comments: "disqus"

  # Customize or translate the strings
  keepReadingStr: "Keep reading"
  backtotopStr: "Back to top"
  shareStr: "Share"
  pageNotFoundTitle: "404 - Page not found"

  authors:
    mcuadros:
      name: Máximo Cuadros
      thumbnail: https://avatars1.githubusercontent.com/u/1573114?v=3&s=460
      bio: "(╯°□°）╯︵ ┻━┻"
      social:
        github: mcuadros
        twitter: mcuadros_
    dripolles:
      name: Daniel Ripollés
      thumbnail: https://avatars1.githubusercontent.com/u/768061?v=3&s=460
      bio: Thinking Hard Driven Development / Loving Python, learning Haskell
      social:
        github: dripolles
        twitter: leidan
    alcortesm:
      name: Alberto Cortés
      thumbnail: https://avatars3.githubusercontent.com/u/9169414?v=3&s=460
      bio: Learning Go (both of them).
      social:
        github: alcortesm
    ikanor:
      name: Franky Rodriguez
      thumbnail: https://avatars2.githubusercontent.com/u/5469238?v=3&s=460
      bio: Computer scientist. Amateur musician. I like math.
      social:
        github: ikanor
        twitter: minifranky
    mvader:
      name: Miguel Molina
      thumbnail: https://avatars3.githubusercontent.com/u/1312023?v=3&s=460
      bio: Code writer (mostly JS and Go) and part-time dragon tamer.
      social:
        github: mvader
        twitter: migrrrr
    scaleyourcode:
      name: Christophe Limpalair
      thumbnail: https://avatars3.githubusercontent.com/u/6696921?v=3&s=460
      bio: "Christophe enjoys sitting down with CTOs and top developers to learn how they work, and sharing that knowledge with the rest of the world. He does this through his podcast called ScaleYourCode."
      social:
        github: christophelimpalair
        twitter: ScaleYourCode
